[Add]バックエンドへのAPI通信機能追加
lxzLocus/ASEticle-Frontend pull request #1
Opened 2024-07-28 04:40 UTC by shonsukee

## 概要
フロントエンドからバックエンドへのAPI通信と結果の表示機能を追加しました．

## 変更点
- 環境変数の導入
- 検索バーとボタン作成
- API通信機能の追加
- 結果の表示

## 影響範囲
- ホームページのレンダリング
- バックエンドへの送信

## 動作要件
- [ ] ルートにあたらしく`.env`を作成して`.env.example`の内容をコピー

## テスト
- Dockerを起動し，以下のコマンド実行
    - `cd ../app/`
    - `yarn run dev`
- Safariで`http://0.0.0.0:49513`にアクセス
    - ※ Google Chromeはデフォルトでは制限がかかっているため`chrome://flags/`で`Block insecure private network requests`を検索しdisabledに変更し適用させる必要があります．
- Searchボタンを押下すると成功アラートと，タイトルが検索バーの下に表示されます．

## 関連Issue
- なし

## 補足
- まだGoogle Scholarとの連携ができていないため，クエリに何を入力しても同一の結果になります．
- **バックエンドの修正も同時に行なったため，両方の環境を揃える必要があります**

2024-07-28 16:34 UTC, lxzLocus commented on src/features/api/FetchScholarInfo.ts
> +			throw new Error('シフトの登録に失敗しました');
エラーメッセージの変更

2024-07-28 16:34 UTC, lxzLocus commented on src/features/api/FetchScholarInfo.ts
> +		console.error("Failed to register draft shifts", error);
エラーメッセージの変更

2024-07-28 16:36 UTC, lxzLocus requested changes
コードクローンされている箇所の，メッセージ変更のみです．
修正をお願いします．

2024-07-29 01:23 UTC, shonsukee commented
@lxzLocus 
エラーメッセージはconsole.log１つ目の日本語に統一でいいですか？
エラーメッセージの形式が決まっていたら教えていただきたいです．

2024-07-29 19:26 UTC, merged